name: Climing Service CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      VAULT_ADDR: http://127.0.0.1:8200
      VAULT_TOKEN: root
      ALLOWED_HOSTS: ${{secrets.ALLOWED_HOSTS}}
      COOKIE_DOMAIN: ${{secrets.COOKIE_DOMAIN}}
      CORS_ALLOWED_ORIGINS: ${{secrets.CORS_ALLOWED_ORIGINS}}
      CSRF_TRUSTED_ORIGINS: ${{secrets.CSRF_TRUSTED_ORIGINS}}
      DB_HOST: 127.0.0.1  # DB_HOSTを127.0.0.1に固定
      DB_PORT: ${{secrets.DB_PORT}}
      DB_USER: ${{secrets.DB_USER}}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DEBUG: ${{secrets.DEBUG}}
      SECRET_KEY: ${{secrets.SECRET_KEY}}

    services:
      vault:
        image: vault:1.13.3
        ports:
          - 8200:8200
        env:
          VAULT_DEV_ROOT_TOKEN_ID: root
        options: "--cap-add=IPC_LOCK"

      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.DB_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.DB_NAME }}
        options: --health-cmd="mysqladmin ping --silent" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
      
      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('backend/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Vault CLI
        run: |
           curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
           sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
           sudo apt-get update && sudo apt-get install vault

      - name: Configure Vault for test
        run: |
          vault kv put secret/data/climbing-service/backend DB_NAME="$DB_NAME" DB_PASSWORD="$DB_PASSWORD" ALLOWED_HOSTS="$ALLOWED_HOSTS" COOKIE_DOMAIN="$COOKIE_DOMAIN" CORS_ALLOWED_ORIGINS="$CORS_ALLOWED_ORIGINS" CSRF_TRUSTED_ORIGINS="$CSRF_TRUSTED_ORIGINS" DB_HOST="$DB_HOST" DB_PORT="$DB_PORT" DB_USER="$DB_USER" DEBUG="$DEBUG" SECRET_KEY="$SECRET_KEY"

      - name: Fetch Vault secrets
        run: |
          vault kv get secret/data/climbing-service/backend
          
      # - name: Set up Python 3.12
      #   uses: actions/setup-python@v4
      #   with:
      #     python-version: '3.12'

      # - name: Install dependencies for mysqlclient
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y pkg-config libmysqlclient-dev build-essential

      # - name: Install Dependencies for Django
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install -r backend/requirements.txt

      # - name: Configure MySQL authentication plugin for localhost
      #   run: |
      #     mysql -u root -p$DB_PASSWORD -h 127.0.0.1 -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '$DB_PASSWORD';"
      #     mysql -u root -p$DB_PASSWORD -h 127.0.0.1 -e "FLUSH PRIVILEGES;"

      # - name: Apply database migrations
      #   run: |
      #     cd backend
      #     python manage.py migrate

      # - name: Load fixtures into the database
      #   run: |
      #     cd backend
      #     python manage.py load_fixtures
