name: Climing Service CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      vault:
        image: vault:1.13.3
        ports:
          - 8200:8200
        env:
          VAULT_DEV_ROOT_TOKEN_ID: root
          VAULT_ADDR: http://127.0.0.1:8200
        options: "--cap-add=IPC_LOCK"

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v3
        with:
          python-version: '3.12'

      - name: Install Vault CLI
        run: |
           curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
           sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
           sudo apt-get update && sudo apt-get install vault

      - name: Configure Vault for test
        env:
            VAULT_ADDR: http://127.0.0.1:8200
            VAULT_TOKEN: root
            ALLOWED_HOSTS: ${{secrets.ALLOWED_HOSTS}}
            COOKIE_DOMAIN: ${{secrets.COOKIE_DOMAIN}}
            CORS_ALLOWED_ORIGINS: ${{secrets.CORS_ALLOWED_ORIGINS}}
            CSRF_TRUSTED_ORIGINS: ${{secrets.CSRF_TRUSTED_ORIGINS}}
            DB_HOST: ${{secrets.DB_HOST}}
            DB_PORT: ${{secrets.DB_PORT}}
            DB_USER: ${{secrets.DB_USER}}
            DEBUG: ${{secrets.DEBUG}}
            SECRET_KEY: ${{secrets.SECRET_KEY}}
            DB_NAME: ${{ secrets.DB_NAME }}
            DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

        run: |
          vault kv put secret test-database DB_NAME=$DB_NA E =$DB_PASSWORD ALLOWED_HOSTS=$ALLOWED_HOSTS COOKIE_DOMAIN=$COOKIE_DOMAIN CORS_ALLOWED_ORIGINS=$CORS_ALLOWED_ORIGINS CSRF_TRUSTED_ORIGINS=$CSRF_TRUSTED_ORIGINS DB_HOST=$DB_HOST DB_PORT=$DB_PORT DB_USER=$DB_USER DEBUG=$DEBUG SECRET_KEY=$SECRET_KEY 

      - name: Retrieve Vault Secret
        env:
          VAULT_ADDR: http://127.0.0.1:8200
          VAULT_TOKEN: root
        run: |
          vault kv get secret/test-database
